"""Clubs core: Club, ClubMember, ClubJoinRequest + club_creation_cost_coins

Revision ID: 0056
Revises: 0055
Create Date: 2026-08-26

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0056"
down_revision: Union[str, None] = "0055"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("game_config", sa.Column("club_creation_cost_coins", sa.Integer(), nullable=False, server_default="500"))

    op.create_table(
        "clubs",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=64), nullable=False, unique=True),
        sa.Column("description", sa.String(length=512), nullable=False, server_default=""),
        sa.Column("club_type", sa.Enum("open", "closed", name="club_type_enum"), nullable=False),
        sa.Column(
            "logo_shape",
            sa.Enum("shield", "circle", "hexagon", "star", "diamond", "banner", "crest", "chevron", name="club_logo_shape_enum"),
            nullable=False,
        ),
        sa.Column("logo_color", sa.String(length=16), nullable=False),
        sa.Column("captain_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("invite_code", sa.String(length=16), nullable=False, unique=True),
        sa.Column("founded_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_clubs_invite_code", "clubs", ["invite_code"])

    op.create_table(
        "club_members",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("club_id", sa.Integer(), sa.ForeignKey("clubs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("role", sa.Enum("captain", "assistant", "member", name="club_role_enum"), nullable=False, server_default="member"),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_club_members_club_id", "club_members", ["club_id"])

    op.create_table(
        "club_join_requests",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("club_id", sa.Integer(), sa.ForeignKey("clubs.id", ondelete="CASCADE"), nullable=False),
        sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "status", sa.Enum("pending", "accepted", "rejected", name="club_join_request_status_enum"),
            nullable=False, server_default="pending",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_club_join_requests_club_id", "club_join_requests", ["club_id"])
    op.create_index("ix_club_join_requests_user_id", "club_join_requests", ["user_id"])
    op.execute(
        "CREATE UNIQUE INDEX uq_club_join_request_pending ON club_join_requests (club_id, user_id) WHERE status = 'pending'"
    )


def downgrade() -> None:
    op.drop_index("uq_club_join_request_pending", table_name="club_join_requests")
    op.drop_table("club_join_requests")
    op.drop_table("club_members")
    op.drop_index("ix_clubs_invite_code", table_name="clubs")
    op.drop_table("clubs")
    op.drop_column("game_config", "club_creation_cost_coins")
    # Matches the drop idiom already established in 0012_card_arena_interactive.py
    # for a handwritten (non-autogenerated) enum-backed migration.
    bind = op.get_bind()
    sa.Enum(name="club_join_request_status_enum").drop(bind, checkfirst=True)
    sa.Enum(name="club_role_enum").drop(bind, checkfirst=True)
    sa.Enum(name="club_logo_shape_enum").drop(bind, checkfirst=True)
    sa.Enum(name="club_type_enum").drop(bind, checkfirst=True)
