/** Human labels for CoinTransaction.type (backend TransactionType). Shared by
 * the profile's transaction history and the admin economy report. */
export const TX_TYPE_LABELS: Record<string, string> = {
  starting_balance: "Стартовый бонус",
  daily_reward: "Ежедневная награда",
  pack_purchase: "Покупка пака",
  card_sale: "Продажа карточки",
  game_reward: "Награда за игру",
  match_reward: "Награда за матч",
  achievement_reward: "Достижение",
  task_reward: "Задание",
  trade_coins_sent: "Обмен: отправлено",
  trade_coins_received: "Обмен: получено",
  admin_adjustment: "Корректировка администратором",
  card_upgrade: "Апгрейд карточки",
  referral_reward: "Реферальная награда",
  collection_reward: "Награда за коллекцию",
  tactico_reward: "Тактико",
  stars_coin_purchase: "Покупка монет за ⭐",
  stars_pack_bonus_coins: "Бонус монет за пак",
  gift_coins: "Подарок",
  wheel_spin_cost: "Колесо: прокрутка",
  wheel_spin_reward: "Колесо: выигрыш",
  fut_draft_entry: "FUT Draft: вход",
  league_reward: "Награда лиги",
  gift_purchase_coins: "Покупка подарка",
  premium_subscription_adjustment: "Проверка подписки на канал",
  bingo_reward: "Бинго",
  club_tournament_match_reward: "Клубный турнир: матч",
  player_tournament_match_reward: "Личный турнир: матч",
  player_tournament_place_reward: "Личный турнир: место",
  tactico_stake_lock: "Тактико: ставка",
  tactico_stake_win: "Тактико: выигрыш ставки",
  tactico_stake_refund: "Тактико: возврат ставки",
  penalty_stake_lock: "Пенальти: ставка",
  penalty_stake_win: "Пенальти: выигрыш ставки",
  penalty_stake_refund: "Пенальти: возврат ставки",
  card_skill_purchase: "Навык карточки",
};
